# Form implementation generated from reading ui file 'checkimagedes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 582)
        MainWindow.setStyleSheet("background-color: #fff9f2;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 651, 521))
        self.groupBox_4.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #fff0e2, /* Màu hồng nhạt góc trên trái */\n"
"    stop:1 #4e80a8  /* Màu xanh dương nhạt góc dưới phải */\n"
");\n"
"border: 1px solid #151515; /* Viền xanh nhạt */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 161, 111))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #7495a9,   /*  (trái trên) */\n"
"        stop:0.5 #83a1b2, /*  (giữa) */\n"
"        stop:1 #b0c9de    /* (phải dưới) */\n"
"    );\n"
"    border: 1px solid #A9A9A9; /* Viền xám nhạt */\n"
"    border-radius: 10px; /* Góc bo tròn */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    padding: 10px; /* Khoảng cách nội bộ */\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 41))
        self.label.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(22, 80, 121, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 30, 121, 111))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #5f849a,   /*  (trái trên) */\n"
"        stop:0.5 #4f8ec1, /*  (giữa) */\n"
"        stop:1 #9fc1de    /* (phải dưới) */\n"
"    );\n"
"    border: 1px solid #A9A9A9; /* Viền xám nhạt */\n"
"    border-radius: 10px; /* Góc bo tròn */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    padding: 10px; /* Khoảng cách nội bộ */\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.label_3.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_3.setObjectName("label_3")
        self.collection_menu = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.collection_menu.setGeometry(QtCore.QRect(20, 80, 81, 22))
        self.collection_menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #91734d; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.collection_menu.setObjectName("collection_menu")
        self.collection_menu.addItem("")
        self.collection_menu.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 30, 291, 111))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #547488,   /*  (trái trên) */\n"
"        stop:0.5 #4982b3, /*  (giữa) */\n"
"        stop:1 #99b9d5    /* (phải dưới) */\n"
"    );\n"
"    border: 1px solid #A9A9A9; /* Viền xám nhạt */\n"
"    border-radius: 10px; /* Góc bo tròn */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    padding: 10px; /* Khoảng cách nội bộ */\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 41))
        self.label_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_2.setObjectName("label_2")
        self.option_menu = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.option_menu.setGeometry(QtCore.QRect(30, 80, 81, 22))
        self.option_menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.option_menu.setObjectName("option_menu")
        self.option_menu.addItem("")
        self.option_menu.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(140, 20, 131, 41))
        self.label_4.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_4.setObjectName("label_4")
        self.entry_name = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.entry_name.setGeometry(QtCore.QRect(150, 80, 121, 20))
        self.entry_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.entry_name.setObjectName("entry_name")
        self.btn_view = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.btn_view.setGeometry(QtCore.QRect(280, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_view.setFont(font)
        self.btn_view.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #f3f8fb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #bee0f5  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.btn_view.setIconSize(QtCore.QSize(16, 16))
        self.btn_view.setObjectName("btn_view")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 601, 291))
        self.label_5.setStyleSheet("QLabel {\n"
"    background-image: url(\"C:/Users/ASUS/Pictures/nen1up.jpg\"); /* Đường dẫn tới hình ảnh */\n"
"    background-repeat: no-repeat; /* Không lặp lại hình ảnh */\n"
"    background-position: center; /* Hình ảnh căn giữa */\n"
"    border: 2px solid #cba387; /* Viền xanh dương nhạt */\n"
"    border-radius: 15px; /* Bo tròn viền, thay đổi giá trị để bo tròn nhiều hoặc ít */\n"
"    padding: 20px; /* Khoảng cách giữa chữ và viền */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    text-align: center; /* Căn chữ giữa */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.groupBox_4)
        self.scrollArea.setGeometry(QtCore.QRect(30, 210, 581, 271))
        self.scrollArea.setStyleSheet("border: 1px solid #a5855e; /* Viền xanh đậm */\n"
"background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Nhâp ngày tháng năm<br/>(YYYY-MM-DD)</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Chọn dữ liệu</p></body></html>"))
        self.collection_menu.setItemText(0, _translate("MainWindow", "Check In"))
        self.collection_menu.setItemText(1, _translate("MainWindow", "Check Out"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Chọn dữ liệu</p></body></html>"))
        self.option_menu.setItemText(0, _translate("MainWindow", "Toàn Bộ"))
        self.option_menu.setItemText(1, _translate("MainWindow", "Nhân Viên"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Nhập tên nhân viên</p></body></html>"))
        self.btn_view.setText(_translate("MainWindow", "Xem"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
