# Form implementation generated from reading ui file 'makedatades.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 567)
        MainWindow.setStyleSheet("background-color: rgb(239, 241, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 631, 481))
        self.groupBox.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #dbe5ed, /* Màu hồng nhạt góc trên trái */\n"
"    stop:1 #c9cdde  /* Màu xanh dương nhạt góc dưới phải */\n"
");\n"
"border: 1px solid #151515; /* Viền xanh nhạt */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.btn_Train = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_Train.setGeometry(QtCore.QRect(530, 40, 81, 41))
        self.btn_Train.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #969ec0, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #5987ab  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid #586393; /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.btn_Train.setObjectName("btn_Train")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 151, 251))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #9ba2c3,   /* Xanh dương nhạt (trái trên) */\n"
"        stop:0.5 #7fa2be /* Be nhạt (giữa) */\n"
"        stop:1 #527ea2\n"
"    );\n"
"    border: 2px solid #6A5ACD; /* Viền tím đậm */\n"
"    border-radius: 10px; /* Góc bo tròn */\n"
"    padding: 10px; /* Khoảng cách nội bộ */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    \n"
"    /* Hiệu ứng đổ bóng */\n"
"    box-shadow: 50px 50px 100px rgba(0, 0, 0, 1); /* X offset, Y offset, Độ mờ, Độ trong suốt */\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_open_camera = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_open_camera.setGeometry(QtCore.QRect(20, 20, 111, 41))
        self.btn_open_camera.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_camera.setFont(font)
        self.btn_open_camera.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #dde0eb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #a5bed1  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.btn_record = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_record.setGeometry(QtCore.QRect(20, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_record.setFont(font)
        self.btn_record.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #dde0eb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #b0c5d7  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.btn_record.setObjectName("btn_record")
        self.btn_cutvideo = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_cutvideo.setGeometry(QtCore.QRect(20, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cutvideo.setFont(font)
        self.btn_cutvideo.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #dde0eb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #c6d5e2  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.btn_cutvideo.setObjectName("btn_cutvideo")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 361, 51))
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(\n"
"        spread:pad, \n"
"        x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #c9cdde,   /* Xanh dương nhạt (trái trên) */\n"
"        stop:0.5 #c0d1df /* Be nhạt (giữa) */\n"
"        stop:1 #8aaac3\n"
"    );\n"
"    border: 2px solid #6A5ACD; /* Viền tím đậm */\n"
"    border-radius: 10px; /* Góc bo tròn */\n"
"    padding: 10px; /* Khoảng cách nội bộ */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    \n"
"    /* Hiệu ứng đổ bóng */\n"
"    box-shadow: 50px 50px 100px rgba(0, 0, 0, 1); /* X offset, Y offset, Độ mờ, Độ trong suốt */\n"
"}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 191, 31))
        self.lineEdit.setStyleSheet("border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 90, 431, 371))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-image: url(\"C:/Users/ASUS/Pictures/khung3.jpg\"); /* Đường dẫn tới hình ảnh */\n"
"    background-repeat: no-repeat; /* Không lặp lại hình ảnh */\n"
"    background-position: center; /* Hình ảnh căn giữa */\n"
"    border: none; /* Loại bỏ viền mặc định */\n"
"    padding: 20px; /* Khoảng cách giữa chữ và viền */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    text-align: center; /* Căn chữ giữa */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_video = QtWidgets.QLabel(parent=self.groupBox)
        self.label_video.setGeometry(QtCore.QRect(190, 100, 413, 351))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_video.setFont(font)
        self.label_video.setStyleSheet("border: 2px solid black;\n"
"border-radius: 5px;\n"
"")
        self.label_video.setObjectName("label_video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.btn_Train.setText(_translate("MainWindow", "Training"))
        self.btn_open_camera.setText(_translate("MainWindow", "Mở camera"))
        self.btn_record.setText(_translate("MainWindow", "Quay"))
        self.btn_cutvideo.setText(_translate("MainWindow", "Cắt Video"))
        self.label.setText(_translate("MainWindow", "Nhập Họ Và Tên:"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_video.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
