# Form implementation generated from reading ui file 'offdes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 451)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 441, 311))
        self.groupBox.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #7ed2ff, /* Màu hồng nhạt góc trên trái */\n"
"    stop:1 #4d7ac6  /* Màu xanh dương nhạt góc dưới phải */\n"
");\n"
"border: 1px solid #151515; /* Viền xanh nhạt */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 91, 351, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 40, 131, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(290, 9, 81, 31))
        self.label_3.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 51, 31))
        self.label_4.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 51, 31))
        self.label_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(190, 250, 75, 41))
        self.pushButton.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #f3f8fb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #bee0f5  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(70, 140, 351, 101))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Nghỉ Phép"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Về Sớm (giờ cụ thể nhập vào dưới)"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Đi Muộn (giờ cụ thể nhập vào dưới )"))
        self.label.setText(_translate("MainWindow", "Nhập Họ Tên"))
        self.label_3.setText(_translate("MainWindow", "Nhập Ngày"))
        self.label_4.setText(_translate("MainWindow", "Lý Do"))
        self.label_2.setText(_translate("MainWindow", "Chọn"))
        self.pushButton.setText(_translate("MainWindow", "Gửi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
