# Form implementation generated from reading ui file 'testmongodes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 681)
        MainWindow.setStyleSheet("background-color: #ddf4ff;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 691, 601))
        self.groupBox_4.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #eeeeee, /* Màu xám rất nhạt */\n"
"    stop:1 #d4d4d4  /* Màu xám nhạt */\n"
");\n"
"border: 1px solid #C0C0C0; /* Viền xám nhạt */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"padding: 10px; /* Khoảng cách nội bộ */\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 321, 111))
        self.groupBox.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #dfdfdf, /* Màu xanh nhạt ở trên */\n"
"    stop:1 #558aad  /* Màu xanh đậm ở dưới */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"padding: 10px; /* Khoảng cách nội bộ */\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(130, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 10, 111, 31))
        self.pushButton.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 rgba(255, 255, 255, 0.8), /* Trắng mờ hơn ở trên */\n"
"    stop:1 rgba(255, 255, 255, 0.4)  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 30, 311, 111))
        self.groupBox_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #e6e6e6, /* Màu xanh nhạt ở trên */\n"
"    stop:1 #6bb0da  /* Màu xanh đậm ở dưới */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"padding: 10px; /* Khoảng cách nội bộ */\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #cfcfcf, /* Màu xanh dương đậm */\n"
"    stop:1 #ffffff /* Màu xanh dương nhạt */\n"
");\n"
"border: 1px solid #357ABD; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 10, 111, 31))
        self.pushButton_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 rgba(255, 255, 255, 0.8), /* Trắng mờ hơn ở trên */\n"
"    stop:1 rgba(255, 255, 255, 0.4)  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid rgba(200, 200, 200, 0.6); /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 59, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 651, 421))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-image: url(\"C:/Users/ASUS/Pictures/khung3up.jpg\"); /* Đường dẫn tới hình ảnh */\n"
"    background-repeat: no-repeat; /* Không lặp lại hình ảnh */\n"
"    background-position: center; /* Hình ảnh căn giữa */\n"
"    border: none; /* Loại bỏ viền mặc định */\n"
"    padding: 20px; /* Khoảng cách giữa chữ và viền */\n"
"    color: #000; /* Màu chữ đen */\n"
"    font-weight: bold; /* Chữ in đậm */\n"
"    text-align: center; /* Căn chữ giữa */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 627, 401))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Checkin"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Họ Và Tên:</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Check  In"))
        self.groupBox_2.setTitle(_translate("MainWindow", "CheckOut"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Họ Và Tên:</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Check Out"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
