# Form implementation generated from reading ui file 'updateifdes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 376)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 251, 311))
        self.groupBox.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:1, \n"
"    stop:0 #b8cedf, /* Màu hồng nhạt góc trên trái */\n"
"    stop:1 #78a3c4  /* Màu xanh dương nhạt góc dưới phải */\n"
");\n"
"border: 1px solid #151515; /* Viền xanh nhạt */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 211, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #345977; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 70, 211, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #345977; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 120, 211, 31))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #345977; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 170, 211, 31))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #345977; /* Viền xanh đậm */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: black; /* Chữ màu trắng */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 220, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #f3f8fb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #bee0f5  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid #3e6b8d; /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:0, y2:1, \n"
"    stop:0 #f3f8fb, /* Trắng mờ hơn ở trên */\n"
"    stop:1 #bee0f5  /* Trắng mờ hơn ở dưới */\n"
");\n"
"border: 1px solid #3e6b8d; /* Viền xám mờ */\n"
"border-radius: 5px; /* Góc bo tròn */\n"
"color: #000; /* Chữ màu đen */\n"
"font-weight: bold; /* Chữ in đậm */\n"
"padding: 5px; /* Khoảng cách nội bộ */\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 302, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Cập Nhật Thông Tin Tại Đây"))
        self.pushButton.setText(_translate("MainWindow", "Chọn Hình Ảnh"))
        self.pushButton_2.setText(_translate("MainWindow", "Cập Nhật Thông Tin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
